# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Metrics/ClassLength:
  Exclude:
    - 'test/*.rb'
    - 'vendor/**/**'
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/AssertOperator:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Minitest/MultipleAssertions:
  Max: 5
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 12
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/BlockLength:
  Max: 28
